name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
