name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install
        run: npm install

      - name: Commitlint current commit
        if: github.event_name == 'push'
        run: npm run commitlint -- --last --verbose

      - name: Commitlint pull request
        if: github.event_name == 'pull_request'
        run: npm run commitlint -- --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

      - name: Typecheck
        run: npm run typecheck

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
